### ISSUE TITLE
New3DS 9.0.0-20E fails to boot if it's turned on without opening the console

### ISSUE THREAD

**Issue by shininchi** [yellows8/3ds_homemenuhax#39] opened 2015-11-02 17:03 UTC
Turning on the console while the lid is open successfully boots into HBL. But, if the you keep the lid closed after pushing the power button,  HomeMenuHax fails to boot and get stuck with bottom screen completely white and top screen black. I don't know if it's useful, but I configured a splash screen using an "imagedisplay.png" file.

**Comment by shininchi** [comment] 2015-11-02 17:06
I forgot to say that this happens since 2.0.
Version 1.0 boots fine with the console closed and open (but fails occasionally)

**Comment by yellows8** [comment] 2015-11-02 17:07
That sounds more like a payload issue. How many times did you try it?

**Comment by shininchi** [comment] 2015-11-02 17:10
Less than 10 in total. But every time I try it with the console opened, it boots fine.
It only fails while booting with the lid closed (bottom screen white and top black)

**Comment by shininchi** [comment] 2015-11-02 17:11
I just tested it again and it keeps failing to boot with the console closed

**Comment by rysian** [comment] 2015-11-12 02:39
I can confirm that the 3ds fails to boot after 30 tries with the lid closed with homemenuhax 2.0 with a custom splash screen. Having the 3ds opened however, fixes the issue. This did not occur with homemenuhax 1.0 with the same payload so it might be an issue with the hax itself.

**Comment by yellows8** [comment] 2015-11-12 02:46
@bobtheglob101 "get stuck with bottom screen completely white and top screen black. " Same for you?

**Comment by rysian** [comment] 2015-11-12 03:39
@yellows8 I'm not too sure if it's white, it might just be my screen being too dark but it may be a light grey for me. It's the same color that the hax first flashes on the bottom screen if I were to let it run with the 3ds open.

Edit: Yeah it's just my screen. It's the exact same thing OP has, white bottom screen and a black top screen. It just stays like that until you preform a force power off.

**Comment by rysian** [comment] 2015-11-18 05:50
Just tested again without a custom boot image, it still freezes up. This bug appears to have no connection to whether a custom boot image is present or not.

**Comment by rysian** [comment] 2015-12-19 05:07
Any updates on this? I've since downgraded to 1.3 (The last version that didn't have this issue) from 2.0

**Comment by yellows8** [comment] 2015-12-19 05:15
"I've since downgraded to 1.3 (The last version that didn't have this issue) from 2.0" Same *hax payloads for both?

I don't really see why you'd turn on the system with the lid closed in the first place tbh.

**Comment by rysian** [comment] 2015-12-20 02:48
@yellows8 Yup, same payload for both 1.3 and 2.0

It's particularly useful when you're just trying to get the 3DS to power on so it can go into sleepmode for Spotpass/Streetpass stuff (at least that's what I do..)

**Comment by shininchi** [comment] 2015-12-28 10:54
@yellows8 In my case, I used to turn it on while keeping the lid closed in order to prevent the 3D glitch that CFWs have. That way, when you open the console the face tracking get reset and works as it should. Also, there's the fact that with less opening/closing the lid, it will last longer.
But, I reckon that this issue is pointless. I just wanted you to know what happens.

Thank you for all your contributions to the scene, as I'm very grateful of what you've accomplished so far. Merry Christmas!

**Comment by profi200** [comment] 2015-12-28 11:50
It's indeed pointless because no one boots a 3DS with closed lid. Ask the CFW authors to fix the problem.

**Closed as completed** 2016-06-13 16:58 UTC
